// Component/regex-game/SuccessModal.jsx
import React from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Sparkles, ArrowRight, Trophy } from "lucide-react";

export default function SuccessModal({
  isOpen,
  level,
  score,
  pointsEarned,
  onNextLevel,
}) {
  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4"
        >
          <motion.div
            initial={{ scale: 0.8, opacity: 0, y: 20 }}
            animate={{ scale: 1, opacity: 1, y: 0 }}
            exit={{ scale: 0.8, opacity: 0, y: 20 }}
            transition={{ type: "spring", damping: 25, stiffness: 300 }}
            className="relative bg-gradient-to-br from-slate-900 to-slate-800 rounded-3xl 
                                 border border-slate-700/50 p-8 max-w-md w-full text-center overflow-hidden"
          >
            {/* Decorative elements */}
            <div
              className="absolute top-0 left-1/2 -translate-x-1/2 w-64 h-64 
                                      bg-gradient-to-b from-cyan-500/20 to-transparent rounded-full blur-3xl"
            />

            <motion.div
              initial={{ scale: 0 }}
              animate={{ scale: 1 }}
              transition={{ delay: 0.2, type: "spring" }}
              className="relative mx-auto w-20 h-20 mb-6"
            >
              <div
                className="absolute inset-0 bg-gradient-to-br from-cyan-400 to-purple-500 
                                          rounded-2xl rotate-6 opacity-50"
              />
              <div
                className="absolute inset-0 bg-gradient-to-br from-cyan-400 to-purple-500 
                                          rounded-2xl flex items-center justify-center"
              >
                <Sparkles className="w-10 h-10 text-white" />
              </div>
            </motion.div>

            <motion.h2
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3 }}
              className="relative text-3xl font-bold text-white mb-2"
            >
              Level Complete!
            </motion.h2>

            <motion.p
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.4 }}
              className="relative text-slate-400 mb-6"
            >
              You've mastered level {level}
            </motion.p>

            <motion.div
              initial={{ opacity: 0, scale: 0.8 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: 0.5 }}
              className="relative flex items-center justify-center gap-3 mb-8"
            >
              <div className="px-4 py-3 bg-emerald-500/20 border border-emerald-500/30 rounded-xl">
                <p className="text-emerald-400 text-2xl font-bold">
                  +{pointsEarned}
                </p>
                <p className="text-emerald-400/60 text-xs">points</p>
              </div>
              <div className="px-4 py-3 bg-yellow-500/20 border border-yellow-500/30 rounded-xl">
                <div className="flex items-center gap-1">
                  <Trophy className="w-5 h-5 text-yellow-400" />
                  <span className="text-yellow-400 text-2xl font-bold">
                    {score}
                  </span>
                </div>
                <p className="text-yellow-400/60 text-xs">total score</p>
              </div>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.6 }}
            >
              <Button
                onClick={onNextLevel}
                className="w-full bg-gradient-to-r from-cyan-500 to-purple-500 
                                         hover:from-cyan-400 hover:to-purple-400 text-white font-semibold
                                         py-6 rounded-xl transition-all shadow-lg shadow-purple-500/25"
              >
                Next Level
                <ArrowRight className="w-5 h-5 ml-2" />
              </Button>
            </motion.div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

// src/components/regex-game/success-modal.vue
<script setup lang="ts">
interface Props {
  modelValue: boolean;
  level: number;
  score: number;
  pointsEarned: number;
}

defineProps<Props>();
const emit = defineEmits<{
  'update:modelValue': [value: boolean];
  nextLevel: [];
}>();

const handleNextLevel = () => {
  emit('update:modelValue', false);
  emit('nextLevel');
};
</script>

<template>
  <v-dialog
    :model-value="modelValue"
    max-width="400"
    persistent
    class="success-modal"
  >
    <v-card class="modal-card">
      <div class="glow-effect"></div>

      <div class="icon-container">
        <div class="icon-bg"></div>
        <div class="icon-main">
          <v-icon size="40" color="white">mdi-sparkles</v-icon>
        </div>
      </div>

      <v-card-title class="modal-title">
        Level Complete!
      </v-card-title>

      <v-card-text class="modal-text">
        You've mastered level {{ level }}
      </v-card-text>

      <div class="stats-row">
        <v-card class="stat-card points" variant="outlined">
          <span class="stat-value">+{{ pointsEarned }}</span>
          <span class="stat-label">points</span>
        </v-card>

        <v-card class="stat-card total" variant="outlined">
          <div class="stat-value-row">
            <v-icon size="20" color="warning">mdi-trophy</v-icon>
            <span class="stat-value">{{ score }}</span>
          </div>
          <span class="stat-label">total score</span>
        </v-card>
      </div>

      <v-card-actions class="modal-actions">
        <v-btn
          block
          size="large"
          class="next-btn"
          @click="handleNextLevel"
        >
          Next Level
          <v-icon class="ml-2">mdi-arrow-right</v-icon>
        </v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<style lang="scss">
.success-modal {
  .modal-card {
    position: relative;
    background: linear-gradient(135deg, rgb(15, 23, 42), rgb(30, 41, 59)) !important;
    border: 1px solid rgba(71, 85, 105, 0.5);
    border-radius: 24px !important;
    padding: 32px;
    text-align: center;
    overflow: hidden;

    .glow-effect {
      position: absolute;
      top: 0;
      left: 50%;
      transform: translateX(-50%);
      width: 256px;
      height: 256px;
      background: linear-gradient(to bottom, rgba(34, 211, 238, 0.2), transparent);
      border-radius: 50%;
      filter: blur(48px);
    }

    .icon-container {
      position: relative;
      width: 80px;
      height: 80px;
      margin: 0 auto 24px;

      .icon-bg {
        position: absolute;
        inset: 0;
        background: linear-gradient(135deg, rgb(34, 211, 238), rgb(168, 85, 247));
        border-radius: 16px;
        transform: rotate(6deg);
        opacity: 0.5;
      }

      .icon-main {
        position: absolute;
        inset: 0;
        display: flex;
        align-items: center;
        justify-content: center;
        background: linear-gradient(135deg, rgb(34, 211, 238), rgb(168, 85, 247));
        border-radius: 16px;
      }
    }

    .modal-title {
      position: relative;
      font-size: 1.875rem !important;
      font-weight: bold;
      color: white;
      text-align: center;
      justify-content: center;
    }

    .modal-text {
      position: relative;
      color: rgb(148, 163, 184);
      text-align: center;
      padding-bottom: 24px;
    }

    .stats-row {
      position: relative;
      display: flex;
      justify-content: center;
      gap: 12px;
      margin-bottom: 32px;

      .stat-card {
        padding: 12px 16px;
        border-radius: 12px !important;
        text-align: center;

        &.points {
          background: rgba(16, 185, 129, 0.2) !important;
          border-color: rgba(16, 185, 129, 0.3) !important;

          .stat-value { color: rgb(52, 211, 153); }
          .stat-label { color: rgba(52, 211, 153, 0.6); }
        }

        &.total {
          background: rgba(234, 179, 8, 0.2) !important;
          border-color: rgba(234, 179, 8, 0.3) !important;

          .stat-value { color: rgb(250, 204, 21); }
          .stat-label { color: rgba(250, 204, 21, 0.6); }
        }

        .stat-value {
          font-size: 1.5rem;
          font-weight: bold;
        }

        .stat-value-row {
          display: flex;
          align-items: center;
          justify-content: center;
          gap: 4px;
        }

        .stat-label {
          font-size: 0.75rem;
          display: block;
        }
      }
    }

    .modal-actions {
      padding: 0;

      .next-btn {
        background: linear-gradient(90deg, rgb(34, 211, 238), rgb(168, 85, 247)) !important;
        color: white !important;
        font-weight: 600;
        border-radius: 12px;
        box-shadow: 0 4px 12px rgba(168, 85, 247, 0.25);
      }
    }
  }
}
</style>
