// client/src/components/regex-game/target-display.vue
<script setup lang="ts">
import type { Target } from './regex-features';

interface Props {
  targets: Target[];
  matchedTargets: number[];
}

defineProps<Props>();
</script>

<template>
  <v-card class="target-display" variant="outlined">
    <v-card-text>
      <div class="header">
        <v-icon size="20" color="purple">mdi-target</v-icon>
        <span>Find these patterns</span>
      </div>

      <div class="targets-list">
        <v-chip
          v-for="(target, index) in targets"
          :key="index"
          :color="matchedTargets.includes(index) ? 'success' : 'default'"
          :variant="matchedTargets.includes(index) ? 'flat' : 'outlined'"
          class="target-chip"
        >
          <v-icon
            size="16"
            :icon="matchedTargets.includes(index) ? 'mdi-check-circle' : 'mdi-circle-outline'"
            class="mr-2"
          />
          <span :class="{ matched: matchedTargets.includes(index) }">
            "{{ target.text }}"
          </span>
          <span
            v-if="matchedTargets.includes(index)"
            class="matched-dot"
          ></span>
        </v-chip>
      </div>

      <div class="tip">
        Tip: Write a single regex that matches all {{ targets.length }} patterns
      </div>
    </v-card-text>
  </v-card>
</template>

<style lang="scss">
.target-display {
  background: rgba(15, 23, 42, 0.6) !important;
  backdrop-filter: blur(12px);
  border-color: rgba(71, 85, 105, 0.5) !important;
  border-radius: 12px !important;

  .header {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-bottom: 16px;
    color: rgb(203, 213, 225);
    font-weight: 500;
  }

  .targets-list {
    display: flex;
    flex-wrap: wrap;
    gap: 12px;
  }

  .target-chip {
    font-family: monospace;
    font-size: 0.875rem;
    position: relative;

    .matched {
      text-decoration: line-through;
      opacity: 0.6;
    }

    .matched-dot {
      position: absolute;
      top: -4px;
      right: -4px;
      width: 12px;
      height: 12px;
      background: rgb(16, 185, 129);
      border-radius: 50%;
    }
  }

  .tip {
    margin-top: 16px;
    font-size: 0.75rem;
    color: rgb(100, 116, 139);
  }
}
</style>

// Component/regex-game/TargetDisplay.jsx
import React from "react";
import { motion } from "framer-motion";
import { Target, CheckCircle2, Circle } from "lucide-react";

export default function TargetDisplay({ targets, matchedTargets }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.2 }}
      className="bg-slate-900/60 backdrop-blur-xl rounded-xl border border-slate-700/50 p-5"
    >
      <div className="flex items-center gap-2 mb-4">
        <Target className="w-5 h-5 text-purple-400" />
        <h3 className="text-slate-300 font-medium">Find these patterns</h3>
      </div>

      <div className="flex flex-wrap gap-3">
        {targets.map((target, index) => {
          const isMatched = matchedTargets.includes(index);
          return (
            <motion.div
              key={index}
              initial={{ scale: 0.8, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              transition={{ delay: 0.1 * index }}
              className={`
                                relative flex items-center gap-2 px-4 py-2 rounded-lg font-mono text-sm
                                transition-all duration-300
                                ${
                                  isMatched
                                    ? "bg-emerald-500/20 border border-emerald-500/50 text-emerald-300"
                                    : "bg-slate-800/80 border border-slate-600/50 text-slate-300"
                                }
                            `}
            >
              {isMatched ? (
                <CheckCircle2 className="w-4 h-4 text-emerald-400" />
              ) : (
                <Circle className="w-4 h-4 text-slate-500" />
              )}
              <span className={isMatched ? "line-through opacity-60" : ""}>
                "{target.text}"
              </span>
              {isMatched && (
                <motion.div
                  initial={{ scale: 0 }}
                  animate={{ scale: 1 }}
                  className="absolute -top-1 -right-1 w-3 h-3 bg-emerald-500 rounded-full"
                />
              )}
            </motion.div>
          );
        })}
      </div>

      <div className="mt-4 text-xs text-slate-500">
        Tip: Write a single regex that matches all {targets.length} patterns
      </div>
    </motion.div>
  );
}
